### ISSUE TITLE
Compilation for .circom failed!

### ISSUE THREAD

**Issue by Subway2023** [whbjzzwjxq/ZKAP#5]
Some circom programs fail to compile. However, when I use circom for compilation, it succeeds. I can confirm that the dependent libraries have been configured correctly.

For example, **spartan-ecdsa-3386b30d9b5b62d8a60735cbeab42bfe42e80429/packages/circuits/eff_ecdsa_membership/eff_ecdsa.circom**.
```
root@6dab9602c3e5:/zkap# python ./eval_detect.py -i ./spartan-ecdsa-3386b30d9b5b62d8a60735cbeab42bfe42e80429/packages/circuits/eff_ecdsa_membership/eff_ecdsa.circom -o ./output
Traceback (most recent call last):
  File "/zkap/./eval_detect.py", line 155, in <module>
    _main()
  File "/zkap/./eval_detect.py", line 151, in _main
    detect(args)
  File "/zkap/./eval_detect.py", line 91, in detect
    raise RuntimeError(f"Compilation for {circom_filename} failed!")
RuntimeError: Compilation for eff_ecdsa.circom failed!
```

**Comment by whbjzzwjxq** [comment]
Hi, Thanks for your continued attention to the repo. Would you mind checking the output from the circom inside the docker to get more information?

**Comment by Subway2023** [comment]
But your Docker doesn't support circom
![1727409294169](https://github.com/user-attachments/assets/bf518751-c872-41e3-aae0-b3b290fa3151)

**Comment by Subway2023** [comment]
```
root@ea8d0fc16878:/zkap# ./circom-219 ./spartan-ecdsa-3386b30d9b5b62d8a60735cbeab42bfe42e80429/packages/circuits/eff_ecdsa_membership/eff_ecdsa.circom
template instances: 16
Everything went okay
```
In this Docker, circom can successfully compile files.  Circom-219 is a circom-linux-amd64 downloaded from GitHub

**Comment by Subway2023** [comment]
Circom2llvm cannot compile many circom files properly.  For example,
```circom
template RotateLeft32Bits(L) {
	signal input in;
	signal output out;

	signal part1 <-- (in << L) & 0xFFFFFFFF;
	signal part2 <-- in >> (32 - L);
	out <== part1 + part2;
	(part1 / 2**L) + (part2 * 2**(32-L)) === in;
}

component main {public [in]} = RotateLeft32Bits(3);
```
## Circom2llvm compile
```
root@ea8d0fc16878:/zkap# circom2llvm --input ./test/benchmarks/RotateLeft32Bits/RotateLeft32Bits.circom --output ./test/output/RotateLeft32Bits --instantiation --arraysize 256

Compiling: ./test/benchmarks/RotateLeft32Bits/RotateLeft32Bits.circom
Output: ./test/output/RotateLeft32Bits/RotateLeft32Bits.ll
thread 'main' panicked at ir_generator/src/info_collector.rs:66:34:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
## Circom compile
```
./test/circomBin/circom-219 ./test/benchmarks/RotateLeft32Bits/RotateLeft32Bits.circom

template instances: 1
Everything went okay
```

**Comment by whbjzzwjxq** [comment]
It is a corner case of the circom2llvm compiler frontend, maybe you can modify the compiler to support the latest Circom version.
